# Generated by Django 6.0.5 on 2026-05-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hojas',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hojas',
            old_name='image',
            new_name='imagen',
        ),
    ]
