# Generated by Django 5.2.14 on 2026-05-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojitas', '0002_rename_decription_hojas_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojas',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hojas',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hojas',
            name='price',
        ),
        migrations.AddField(
            model_name='hojas',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='hojas',
            name='nombre',
            field=models.CharField(default=None, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='hojas',
            name='precio',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='hojas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hojas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
