# Generated by Django 6.0.5 on 2026-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojitas', '0003_remove_hojas_description_remove_hojas_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hojas',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hojas',
            old_name='precio',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='hojas',
            name='nombre',
        ),
        migrations.AddField(
            model_name='hojas',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='hojas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='hojitas/', verbose_name='Imagen'),
        ),
    ]
